services: 
  database: 
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always

    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
  web:
    depends_on:
      - database
    build: .